Replace echo with printf (for strict POSIX compliance).

diff --git a/tools/plot_diff b/tools/plot_diff
--- a/tools/plot_diff
+++ b/tools/plot_diff
@@ -59,7 +59,7 @@ while [ "$1" ] ; do
 	;;
 
     -* )
-	echo "${ME}: unknown option \(ignored\): $1" 2>&1
+	printf "${ME}: unknown option \(ignored\): $1\n" 2>&1
 	;;
     *)
 	if [ -z "${FILE1}" ]; then
@@ -69,7 +69,7 @@ while [ "$1" ] ; do
 	    FILE2=$1
 	    FILENAME2=${FILE2}
 	else
-	    echo "${ME}: too many filenames \(ignored\): $1" 2>&1
+	    printf "${ME}: too many filenames \(ignored\): $1\n" 2>&1
 	fi
 	;;
     esac
@@ -77,7 +77,7 @@ while [ "$1" ] ; do
 done
 
 if [ -z "${FILE1}" -o -z "${FILE2}" ]; then
-    echo "usage: ${ME} file1.dat file2.dat > plot.pdf" 1>&2
+    printf "usage: ${ME} file1.dat file2.dat > plot.pdf\n" 1>&2
     exit 1
 fi
 
@@ -89,7 +89,7 @@ DIFF=`mktemp diff.XXX`
 ${TOOLS}/diff_log ${FILE1} ${FILE2} > ${DIFF}
 
 if [ $? -ne 0 ]; then
-    echo "${ME}: an error occurred in diff_log" 1>&2
+    printf "${ME}: an error occurred in diff_log\n" 1>&2
     exit 1
 fi
 
diff --git a/tools/plot_steps b/tools/plot_steps
--- a/tools/plot_steps
+++ b/tools/plot_steps
@@ -6,7 +6,7 @@ ME=`basename $0`
 COMMAND="$@"
 
 if [ -z "${COMMAND}" ]; then
-    echo "example usage: ${ME} ./prog.byte -sundialsI -maxt 10 -debugz > plot.pdf" 1>&2
+    printf "example usage: ${ME} ./prog.byte -sundialsI -maxt 10 -debugz > plot.pdf\n" 1>&2
     exit 1
 fi
 
@@ -22,9 +22,9 @@ fi
 if grep -vq '/^.*find(\(.*\), .*).*/' ${DATAFILE}; then
     true
 else
-    echo "This script requires the logging of microsteps to stdout." 1>&2
-    echo "  - for most solvers, use the option: -debugz" 1>&2
-    echo "  - but a patched version of sundials is required." 1>&2
+    printf "This script requires the logging of microsteps to stdout.\n" 1>&2
+    printf "  - for most solvers, use the option: -debugz\n" 1>&2
+    printf "  - but a patched version of sundials is required.\n" 1>&2
     rm -f ${DATAFILE} ${TIMEFILE}
     exit 2
 fi
